### ISSUE TITLE
[FEATURE REQUEST] Add Funimation

### ISSUE THREAD

**Issue by Oujiii** [Kaway/getyouranimes#44]
Basically the title, Funimation has a lot of animes, so it would be good to have them.

**Comment by Kaway** [comment]
Thanks for the request. I'll check for it in the coming days

**Comment by Kaway** [comment]
Hum, it will take me more time than usual because they block people depending on their country, so I'll have to check if I can use a public proxy to scrap their website, hoping that they don't block proxies

**Comment by Oujiii** [comment]
Thank you for taking the time to look into ths. I can provide you a wireguard conf to a US VPN provider so you can do the testing if you want to. You may also use [ControlD](https://controld.com/), get their free trial and you can redirect any DNS request to funimation to the US and it should work (that's how I download my stuff usually).

**Comment by Kaway** [comment]
Hey again, I added Funimation to the list. The link is maybe broken, I'll check it tomorrow.

**Comment by Oujiii** [comment]
It looks like it is working. Just a question before closing this issue, it should be assumed that the list this is scrapping from is for animes available on the US, correct? This would apply for Crunchyroll too, I assume. Just asking this as those websites supports more than one countries and not everything that is available in one country, is on the other.

Thank you again for the hard work, I really appreciate it!

**Comment by Kaway** [comment]
For Funimation, their main domain is geo-blocked by location but their api is not, therefore we can assume it's only for US.
It's almost the same for Crunchyroll, without geo-blocking ... They list all their animes without specifying in which country it is really available. Btw, concerning Crunchyroll, the index is really outdated because they use Cloudflare and I have problem by-passing they bot protection, but I'll be working on it soon.
